# Generated by Django 2.2.6 on 2019-11-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['user__username']},
        ),
    ]
