# Generated by Django 2.2.6 on 2019-11-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191101_2130'),
        ('users', '0002_auto_20191103_1854'),
    ]

    operations = [
    ]
