# Generated by Django 2.2.5 on 2019-09-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=60)),
                ('data_inicio', models.DateField(blank=True)),
                ('hora_inicio', models.TimeField()),
                ('data_fim', models.DateField(blank=True)),
                ('hora_fim', models.TimeField()),
            ],
        ),
    ]
