# Generated by Django 2.2.2 on 2019-09-27 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20190927_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
