# Generated by Django 2.2.2 on 2019-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_evento_id_alimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='id_categoria',
            field=models.ManyToManyField(to='evento.Categoria'),
        ),
    ]
